### ISSUE TITLE
关于svg图标大小问题

### ISSUE THREAD

**Issue by Ephemeralwanning** [Cheukfung/pyqt-fluent-widgets-template#2]
在 [https://fluenticons.co/outlined](https://fluenticons.co/outlined) 下载的svg显示很小
![QQ截图20230504151228](https://user-images.githubusercontent.com/104692238/236135433-59a82b7c-acdf-4dae-a790-1abdb732ab89.png)
`<svg width="24" height="24" fill="none" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M3 5.75A2.75 2.75 0 0 1 5.75 3h9.964a3.25 3.25 0 0 1 2.299.952l2.035 2.035c.61.61.952 1.437.952 2.299v3.736a6.471 6.471 0 0 0-1.5-.709V8.287c0-.465-.184-.91-.513-1.238l-2.035-2.035a1.75 1.75 0 0 0-.952-.49V7.25a2.25 2.25 0 0 1-2.25 2.25h-4.5A2.25 2.25 0 0 1 7 7.25V4.5H5.75c-.69 0-1.25.56-1.25 1.25v12.5c0 .69.56 1.25 1.25 1.25H6v-5.25A2.25 2.25 0 0 1 8.25 12h5.784a6.534 6.534 0 0 0-1.658 1.5H8.25a.75.75 0 0 0-.75.75v5.25h3.813c.173.534.412 1.037.709 1.5H5.75A2.75 2.75 0 0 1 3 18.25V5.75ZM8.5 4.5v2.75c0 .414.336.75.75.75h4.5a.75.75 0 0 0 .75-.75V4.5h-6Zm14.5 13a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0Zm-8.5-.5a.5.5 0 0 0 0 1h4.793l-1.647 1.646a.5.5 0 0 0 .708.708l2.5-2.5a.5.5 0 0 0 0-.708l-2.5-2.5a.5.5 0 0 0-.708.708L19.293 17H14.5Z" fill="#212121"/></svg>`
我尝试修改width="24" height="24"的值没反应 viewBox="0 0 24 24" 24改为48变得更小了 改为12只显示左上角，有什么办法可以使图标等比例放大嘛

**Comment by Cheukfung** [comment]
试试 width和viewbox都改为48

**Comment by Cheukfung** [comment]
我用的iconpark https://iconpark.oceanengine.com/official
