### ISSUE TITLE
请教一下mac上的打包命令

### ISSUE THREAD

**Issue by Ephemeralwanning** [Cheukfung/pyqt-fluent-widgets-template#3]
我用以下命令在mac虚拟机下打包应用后执行会跳出一个控制台，不会出现相应的gui，直接运行py文件则窗口正常。
是我使用的命令不对吗？
![QQ截图20230506210520](https://user-images.githubusercontent.com/104692238/236626084-244eaf19-3989-45d8-b161-a6fa5631c471.png)
![QQ截图20230506210647](https://user-images.githubusercontent.com/104692238/236626086-944e72ce-bb95-4a0b-bdac-2950bc23eb8f.png)

**Comment by Cheukfung** [comment]
我还没在macos打包过，我找个时间试试

**Comment by Cheukfung** [comment]
最近工作比较忙，现在才有时间高，你试试这个
```bash
nuitka --standalone --onefile --plugin-enable=pyqt5 --output-dir=out --disable-console --macos-create-app-bundle --macos-app-mode=gui --macos-app-icon=resource/images/logo.icns --macos-app-version==0.0.1 --follow-import-to=common,components,view entry.py
```
