### ISSUE TITLE
有计划更新适配新版的fluent_widget嘛

### ISSUE THREAD

**Issue by Ephemeralwanning** [Cheukfung/pyqt-fluent-widgets-template#4]
新版的写法有点不一样了，导航栏还有tooltip

**Comment by Cheukfung** [comment]
新版的导航栏用了简单的路由，不过我自己用不上就没加进去，tooltip加进去了。
还有可搜索的titlebar也加进去了，也更新了多线程的方法。注意：我的代码水平不高，仅仅建议用在无关紧要的小工具中。
<img width="600" alt="main_window" src="https://github.com/Cheukfung/pyqt-fluent-widgets-template/assets/14865236/81ea8bbd-990f-4865-b4ac-5f4f2d2e3500">
<img width="600" alt="微信截图_20230625004544" src="https://github.com/Cheukfung/pyqt-fluent-widgets-template/assets/14865236/254fa51f-5a0d-4cab-8a67-78984c9dfac5">
